name: E2E

# Controls when the action will run.
on: [push, pull_request]

jobs:
  build-database:
    name: Build Mysql Database
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create default user
      run: |
        mysql --version
        sudo service mysql restart
        mysql -uroot -proot -e "CREATE USER '$(whoami)'@'localhost';"
        mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO '$(whoami)'@'localhost';"
    - name: mysql-data
      run: | 
        ./dev-support/database/init-database.sh
        ./dev-support/travis/install_external_dependencies.sh
  build-submarine:
    name: Build Submarine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Set up Maven 3.6.3
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3
      - name: Check version
        run: |
          mvn --version
          java -version
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository/com1
          key: ${{ runner.os }}-maven-com-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-com-
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository/org
          key: ${{ runner.os }}-maven-org-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-org-
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository/net
          key: ${{ runner.os }}-maven-net-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-net-
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository/io
          key: ${{ runner.os }}-maven-io-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-io-
      - name: Build with Maven
        run: |
          export MAVEN_OPTS="-Xmx2g -XX:ReservedCodeCacheSize=512m  -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN"
          mvn --no-transfer-progress -DskipTests install
  test-e2e:
    name: Test E2E
    needs: [build-database, build-submarine]
    runs-on: ubuntu-latest
    env:
      TEST_FLAG: "verify -DskipRat -am"
      TEST_MODULES: "-pl org.apache.submarine:submarine-test-e2e"
      TEST_PROJECTS: ""
    steps:
      - uses: actions/checkout@v2
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: verify
        run: | 
          if [[ -n $TEST_MODULES ]]; then export MODULES="${TEST_MODULES}"; fi
          echo ">>> mvn $TEST_FLAG $MODULES $PROFILE -B $TEST_PROJECTS"
          mvn $TEST_FLAG $MODULES $PROFILE -B $TEST_PROJECTS
      - name: test
        run: mvn $TEST_FLAG $MODULES $PROFILE -B $TEST_PROJECTS
