name: Mysql

# Controls when the action will run.
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - "8888:3306"
    steps:
    - name: mysql-start
      run: sudo service mysql restart
    - name: mysql-status1
      run:
        sudo service mysql status
# #         sudo mysqladmin -u root -p root password
    - name: mysql-test
      run:
        sudo mysql --port 8888 -e "CREATE DATABASE IF NOT EXISTS submarine_test;"
#     - name: mysql-data
#       run: sudo ./dev-support/database/init-database.sh
#       - name: Shutdown Ubuntu MySQL (SUDO)
#         run: sudo service mysql stop
#       - name: mysql-status2
#         run: sudo service mysql status
#       - name: mysql-start
#         run: |
#           sudo service mysql start
          
#       - name: mysql-status3
#         run: sudo service mysql status
