name: Mysql

# Controls when the action will run.
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create default user
      run: |
        mysql --version
        sudo service mysql restart
        mysql -uroot -proot -e "CREATE USER '$(whoami)'@'localhost';"
        mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO '$(whoami)'@'localhost';"
    - name: mysql-data
      run: | 
        ./dev-support/database/init-database.sh
        ./dev-support/travis/install_external_dependencies.sh
