name: Mysql

# Controls when the action will run.
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#     - name: mysql-start
#       run: sudo service mysql start
#     - name: mysql-status1
#       run:
#         sudo service mysql status
# #         sudo mysqladmin -u root -p root password
#     - name: mysql-test
#       run: |
#         sudo su
#         mysql -e "CREATE DATABASE IF NOT EXISTS submarine_test;"
#         exit
#     - name: mysql-data
#       run: sudo ./dev-support/database/init-database.sh
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '5.7'
      - run: sudo mysql -e 'CREATE DATABASE IF NOT EXISTS submarine_test;'
#       - name: mysql-status2
#         run: sudo service mysql status
#       - name: mysql-start
#         run: |
#           sudo service mysql start
          
#       - name: mysql-status3
#         run: sudo service mysql status
