name: submarine-submitter

on: [push]

jobs:
  submarine-submitter:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        hadoop-version: ["2.9"]
      # max-parallel: 2
      # fail-fast: false
    # services:
    #   mysql:
    #     image: mysql:5.7
    #     env:
    #       MYSQL_ROOT_PASSWORD: "password"
    #     ports:
    #       - 3306:3306
    #     options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 10s --health-retries 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Set up Protobuf 3.10.1
        uses: arduino/setup-protoc@v1
        with:
          version: "3.10.1"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: "1.8"
      - name: Set up Maven 3.6.3
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3
      - name: Check version
        run: |
          mvn --version
          java -version
      # - name: Prepate default mysql-data
      #   run: |
      #     python3 -V
      #     pip install mysql-connector-python
      #     python3 ./dev-support/database/init-database.py
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      # - uses: actions/cache@v1
      #   with:
      #     path: ~/.m2/repository/com1
      #     key: ${{ runner.os }}-maven-com-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-maven-com-
      # - uses: actions/cache@v1
      #   with:
      #     path: ~/.m2/repository/org
      #     key: ${{ runner.os }}-maven-org-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-maven-org-
      # - uses: actions/cache@v1
      #   with:
      #     path: ~/.m2/repository/net
      #     key: ${{ runner.os }}-maven-net-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-maven-net-
      # - uses: actions/cache@v1
      #   with:
      #     path: ~/.m2/repository/io
      #     key: ${{ runner.os }}-maven-io-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-maven-io-
      - name: Build
        env:
          BUILD_FLAG: "clean package install -DskipTests -DskipRat -ntp"
          MODULES: "-pl !:submarine-submitter-k8s,!:submarine-workbench,!:submarine-workbench-web,!:submarine-cloud,!:submarine-dist"
          PROFILE: "-Phadoop-${{ matrix.hadoop-version }}"
        run: |
          export MAVEN_OPTS="-Xmx2g -XX:ReservedCodeCacheSize=1024m  -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN"
          echo ">>> mvn $BUILD_FLAG $MODULES $PROFILE -B"
          mvn $BUILD_FLAG $MODULES $PROFILE -B
      - name: Test
        env:
          TEST_FLAG: "test -DskipRat -am -ntp"
          TEST_MODULES: -pl !:submarine-submitter-k8s,!:submarine-workbench,!:submarine-workbench-web,!:submarine-cloud,!:submarine-commons-cluster,!:submarine-commons-metastore,!:submarine-commons-rpc,!:submarine-commons-runtime,!:submarine-commons-utils,!:submarine-dist,!:submarine-test,!:submarine-test-e2e,!:submarine-test-k8s,!:submarine-all,!:submarine-server-api,!:submarine-server-core,!:submarine-server-rpc,!:submarine-spark-security
          PROFILE: "-Phadoop-${{ matrix.hadoop-version }}"
          TEST_PROJECTS: ""
        run: |
          echo ">>> mvn $TEST_FLAG $TEST_MODULES $PROFILE -B $TEST_PROJECTS"
          mvn $TEST_FLAG $TEST_MODULES $PROFILE -B $TEST_PROJECTS
