name: submarine-workbench

on: [push]

jobs:
  submarine-workbench:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Set up Maven 3.6.3
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Set up Chrome latest
        uses: browser-actions/setup-chrome@latest
      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest
      - name: Check version
        run: |
          mvn --version
          node --version
          npm --version
          chrome --version
          firefox --version
      - name: Maven Build
        env:
          BUILD_FLAG: "clean package -DskipTests -ntp"
          MODULES: "-pl org.apache.submarine:submarine-workbench-web"
        run: |
          mvn $BUILD_FLAG $MODULES -B
      - name: Install
        working-directory: ./submarine-workbench/workbench-web
        run: |
          npm install
      - name: Test with chrome
        working-directory: ./submarine-workbench/workbench-web
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - name: Test with firefox
        working-directory: ./submarine-workbench/workbench-web
        run: npm run test -- --no-watch --no-progress --browsers=FirefoxHeadless
