name: submarine-submitter

on: [push]

jobs:
  submarine-submitter:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        spark-version: [2.3, 2.4, 3.0]
        range-version: [1.2, 2.0]
        exclude:
          - spark-version: 2.3
            range-version: 1.2
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Set up Protobuf 3.10.1
        uses: arduino/setup-protoc@v1
        with:
          version: "3.10.1"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: "1.8"
      - name: Set up Maven 3.6.3
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3
      - name: Check version
        run: |
          mvn --version
          java -version
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository/com1
          key: ${{ runner.os }}-maven-com-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-com-
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository/org
          key: ${{ runner.os }}-maven-org-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-org-
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository/net
          key: ${{ runner.os }}-maven-net-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-net-
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository/io
          key: ${{ runner.os }}-maven-io-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-io-
      - name: Build
        env:
          BUILD_FLAG: "--batch-mode clean install -Dmaven.javadoc.skip=true -ntp"
          MODULES: "-pl :submarine-spark-security"
          PROFILE: "-Pspark-${{matrix.spark-version}} -Pranger--${{matrix.range-version}}"
        run: |
#          export MAVEN_OPTS="-Xmx2g -XX:ReservedCodeCacheSize=512m  -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN"
          mvn $BUILD_FLAG $MODULES $PROFILE -B
      - name: Test
        env:
          TEST_FLAG: "--batch-mode clean install -Dmaven.javadoc.skip=true -ntp"
          TEST_MODULES: "-pl :submarine-spark-security"
          PROFILE: "-Pspark-${{matrix.spark-version}} -Pranger--${{matrix.range-version}}"
          TEST_PROJECTS: ""
        run: |
          mvn $TEST_FLAG $TEST_MODULES $PROFILE -B $TEST_PROJECTS
