name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: SETUP
      run: |
        sudo service mysql restart
        sudo mysql -u root
        exit
      env:
        DB_PORT: 3306
    - name: The job has failed
      if: ${{ failure() }}
      run: |
        systemctl status mysql.service
