name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306

    steps:
    - uses: actions/checkout@v2
    - name: SETUP
      run: |
        sudo service mysql start
        ./dev-support/database/init-database.sh
        mysql -e "CREATE DATABASE IF NOT EXISTS submarine_test;"
        mysql -e "CREATE USER IF NOT EXISTS 'submarine_test'@'%' IDENTIFIED BY 'password_test';"
        mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'submarine_test'@'%';"
        mysql -e "use submarine_test; source ./submarine.sql; show tables;"
      env:
        DB_PORT: 3306
